version: 1
project:
  exports:
    - id: full-book-pdf
      format: typst
      template: https://github.com/myst-templates/plain_typst_book.git
      output: exports/modul-biotek-praktikum_25.pdf
      cover: content/figures/logo.svg
      logo: content/figures/logo.svg
      show_ToC: true
      ToC_depth: 2
      papersize: a4
  downloads:
    - id: full-book-pdf
      title: Unduh Buku Lengkap (PDF)