"""Generate MyST markdown fragments from per-lesson procedure workbooks.

Run before `jupyter book build`; the generated files are build artifacts.

Each lesson folder owns one `xlsx_sources.yaml`, sitting next to its own
workbook -- e.g. content/01-isolasi_dna/xlsx_sources.yaml alongside
content/01-isolasi_dna/dnaisolation-procedure.xlsx. This script discovers
every such config under content/ and processes each independently: a
mistake in one lesson's config does not block generation for the others.

Within one config, sheet 1 is the single source of truth for procedure
text. Every procedure row carries a stable Step ID. Per-sample detail
sheets (Alat / Lokasi) reference those IDs instead of duplicating text.

To add a new lesson: copy an existing xlsx_sources.yaml into the new
lesson folder, point `workbook:` at that folder's spreadsheet, adjust
`targets:`. Nothing outside that folder needs to change.
"""

import re
import sys
from pathlib import Path

import openpyxl
import yaml

REPO = Path(__file__).resolve().parent.parent
CONFIG_GLOB = "content/**/xlsx_sources.yaml"

# Excel spills empty source cells as 0 when a whole-column formula is used;
# treat those as blank too, alongside genuinely empty cells.
BLANK_VALUES = {None, "", 0}

# Leading "1." / "12)" / "3 - " that were typed by hand into the cell text.
LEADING_NUMBER = re.compile(r"^\s*\d+\s*[.)\-]\s*")

# "P-03..P-05" -> inclusive range. Both ends must share a prefix.
ID_RANGE = re.compile(r"^\s*([A-Za-z\-]*?)(\d+)\s*\.\.\s*([A-Za-z\-]*?)(\d+)\s*$")

BANNER = "<!-- GENERATED by scripts/xlsx_to_markdown.py -- do not edit by hand -->"

warnings: list = []


def warn(message: str) -> None:
    warnings.append(message)
    print(f"  warning: {message}")


def clean(value) -> str:
    """Normalise one cell to a plain string; '' means blank."""
    if value in BLANK_VALUES:
        return ""
    text = str(value)
    # Excel loves non-breaking spaces; they survive into the PDF as odd gaps.
    text = text.replace("\xa0", " ")
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = "\n".join(re.sub(r"[ \t]+", " ", line).strip() for line in text.split("\n"))
    return text.strip(" \t\n`")


def header_map(ws, header_row: int) -> dict:
    """{header text: column index} for one header row."""
    out = {}
    for col in range(1, ws.max_column + 1):
        name = clean(ws.cell(header_row, col).value)
        if name:
            out[name] = col
    return out


def used_rows(ws, first_data_row: int, columns: list, hard_cap: int = 5000) -> int:
    """Last row with real content.

    ws.max_row is meaningless if a sheet ever held a whole-column array
    formula -- it reports 1,048,576. Scan for the real end instead.
    """
    last = first_data_row - 1
    for row in range(first_data_row, min(ws.max_row, hard_cap) + 1):
        if any(clean(ws.cell(row, c).value) for c in columns):
            last = row
    return last


def require(headers: dict, name: str, sheet: str) -> int:
    if name not in headers:
        raise SystemExit(
            f"column {name!r} not found in sheet {sheet!r} (found: {sorted(headers)})"
        )
    return headers[name]


def read_source(wb, spec: dict, sample: str) -> dict:
    """Index sheet 1 by Step ID for one sample column.

    Returns {step_id: {"n", "alur", "text", "order"}} containing only the
    steps that sample actually performs, numbered 1..N in sheet order.
    """
    ws = wb[spec["sheet"]]
    headers = header_map(ws, spec["header_row"])
    c_id = require(headers, spec["id_column"], ws.title)
    c_text = require(headers, sample, ws.title)
    c_alur = headers.get(spec.get("group_column", ""))

    first = spec["first_data_row"]
    last = used_rows(ws, first, sorted(headers.values()))

    index, alur, n, order = {}, "", 0, 0
    for row in range(first, last + 1):
        # Alur is written once per phase, then left blank -- carry it down.
        if c_alur:
            here = clean(ws.cell(row, c_alur).value)
            if here:
                alur = here
        text = LEADING_NUMBER.sub("", clean(ws.cell(row, c_text).value))
        if not text:
            continue
        step_id = clean(ws.cell(row, c_id).value)
        if not step_id:
            warn(f"{ws.title!r} row {row}: {sample} text has no Step ID, skipped")
            continue
        if step_id in index:
            warn(f"{ws.title!r} row {row}: duplicate Step ID {step_id!r}")
        n += 1
        order += 1
        index[step_id] = {"n": n, "alur": alur, "text": text, "order": order}
    return index


def expand_ids(spec: str) -> list:
    """'P-03..P-05' or 'P-01, P-04' -> ['P-03','P-04','P-05'] / ['P-01','P-04']."""
    out = []
    for part in re.split(r"[,\n]", spec):
        part = part.strip()
        if not part:
            continue
        match = ID_RANGE.match(part)
        if match:
            prefix, start, prefix2, end = match.groups()
            if prefix != prefix2:
                warn(f"range {part!r} mixes prefixes {prefix!r}/{prefix2!r}")
            width = len(start)
            out += [f"{prefix}{i:0{width}d}" for i in range(int(start), int(end) + 1)]
        else:
            out.append(part)
    return out


def format_numbers(nums: list) -> str:
    """[3,4,5] -> '3-5'   [3,5] -> '3, 5'"""
    if not nums:
        return ""
    nums = sorted(nums)
    if len(nums) > 1 and nums == list(range(nums[0], nums[-1] + 1)):
        return f"{nums[0]}-{nums[-1]}"
    return ", ".join(str(n) for n in nums)


def emit_cells(out: list, cells: list) -> None:
    """One list-table row; cells may contain newlines."""
    for i, cell in enumerate(cells):
        marker = "* - " if i == 0 else "  - "
        body = (cell or "").split("\n")
        out.append(f"{marker}{body[0]}")
        for extra in body[1:]:
            out.append(f"    {extra}" if extra else "")


def as_list(wb, target: dict) -> str:
    """One sample column -> a numbered markdown list, grouped by Alur."""
    index = read_source(wb, target["source"], target["column"])
    steps = sorted(index.values(), key=lambda s: s["order"])

    lines, current = [BANNER, ""], None
    for step in steps:
        if step["alur"] != current:
            current = step["alur"]
            if current:
                lines += ["", f"**{current}**", ""]
        body = step["text"].split("\n")
        lines.append(f"{step['n']}. {body[0]}")
        for extra in body[1:]:
            lines.append(f"   {extra}" if extra else "")
    lines.append("")
    return "\n".join(lines)


def as_detail(wb, target: dict) -> str:
    """A per-sample Alat/Lokasi sheet, joined back to the procedure text."""
    source = target["source"]
    sample = target["column"]
    index = read_source(wb, source, sample)

    ws = wb[target["sheet"]]
    headers = header_map(ws, target["header_row"])
    c_id = require(headers, target["id_column"], ws.title)
    extra_names = list(target["extra_columns"])
    extra_cols = [require(headers, n, ws.title) for n in extra_names]

    first = target["first_data_row"]
    last = used_rows(ws, first, sorted(headers.values()))

    rows, seen = [], set()
    for row in range(first, last + 1):
        raw = clean(ws.cell(row, c_id).value)
        if not raw:
            continue
        found = []
        for step_id in expand_ids(raw):
            if step_id not in index:
                warn(
                    f"{ws.title!r} row {row}: Step ID {step_id!r} has no "
                    f"{sample} procedure in {source['sheet']!r}"
                )
                continue
            found.append(index[step_id])
            seen.add(step_id)
        if not found:
            continue
        found.sort(key=lambda s: s["order"])
        alurs = list(dict.fromkeys(s["alur"] for s in found if s["alur"]))
        if len(found) == 1:
            text = found[0]["text"]
        else:
            # Merged row: show each step as its own bullet inside the cell.
            text = "\n".join(f"- {s['n']}. {s['text']}" for s in found)
        rows.append(
            {
                "order": found[0]["order"],
                "cells": [
                    " / ".join(alurs),
                    format_numbers([s["n"] for s in found]),
                    text,
                    *[clean(ws.cell(row, c).value) for c in extra_cols],
                ],
            }
        )

    missing = [i for i in index if i not in seen]
    if missing:
        warn(
            f"{len(missing)} {sample} step(s) have no {ws.title!r} entry: "
            + ", ".join(sorted(missing)[:8])
            + (" ..." if len(missing) > 8 else "")
        )

    rows.sort(key=lambda r: r["order"])

    out = [BANNER, ""]
    caption = target.get("caption", "")
    out.append(f":::{{list-table}} {caption}".rstrip())
    if target.get("label"):
        out.append(f":label: {target['label']}")
    out.append(":header-rows: 1")
    out.append("")
    emit_cells(out, [target.get("group_header", "Alur"), "No", "Prosedur", *extra_names])
    for row in rows:
        emit_cells(out, row["cells"])
    out += [":::", ""]
    return "\n".join(out)


def process_config(config_path: Path) -> bool:
    """Run one lesson's xlsx_sources.yaml. Returns True on success."""
    lesson = config_path.parent
    print(f"\n=== {config_path.relative_to(REPO)} ===")
    try:
        config = yaml.safe_load(config_path.read_text(encoding="utf-8"))

        # Paths in a lesson's config are relative to that lesson's folder,
        # not the repo root -- copy-pasting a config to a new lesson needs
        # no path surgery.
        workbook = (lesson / config["workbook"]).resolve()
        if not workbook.exists():
            raise SystemExit(f"workbook not found: {workbook}")

        outdir = (lesson / config.get("outdir", "_generated")).resolve()
        outdir.mkdir(parents=True, exist_ok=True)

        # data_only=True reads the values Excel last cached -- openpyxl
        # cannot evaluate formulas itself.
        wb = openpyxl.load_workbook(workbook, data_only=True)

        defaults = config.get("source", {})
        for target in config["targets"]:
            target.setdefault("source", defaults)
            sheet = target.get("sheet", target["source"]["sheet"])
            if sheet not in wb.sheetnames:
                raise SystemExit(f"sheet {sheet!r} not in {wb.sheetnames}")
            render = {"list": as_list, "detail": as_detail}[target["kind"]]
            text = render(wb, target)
            dest = outdir / target["out"]
            dest.write_text(text, encoding="utf-8")
            print(f"wrote {dest.relative_to(REPO)} ({len(text.splitlines())} lines)")
        return True
    except SystemExit as e:
        print(f"  ERROR: {e}")
        return False


def main() -> None:
    configs = sorted(REPO.glob(CONFIG_GLOB))
    if not configs:
        print(f"no {CONFIG_GLOB} found -- nothing to generate")
        return

    ok = True
    for config_path in configs:
        warnings.clear()
        if not process_config(config_path):
            ok = False
        elif warnings:
            print(f"  {len(warnings)} warning(s) -- see above")

    if not ok:
        raise SystemExit(1)


if __name__ == "__main__":
    sys.exit(main())